#+TITLE: bin 
Useful scripts or something
* [[./brewup][brewup]]
Update everything brew, run cleanup, prune, and doctor,
run [[./mkmasterinstall][mkmasterinstall]]

* [[./masterinstall][masterinstall]]
A file generated by [[./mkmasterinstall][mkmasterinstall]] to install homebrew and everything I've
=brew=, =brew cask=, and =pip= installed. I imagine it will be handy in the
event that I want to get a new computer and not install from previous
backup. Idk, there's probably a much simpler way of doing this.

* [[./mkmasterinstall][mkmasterinstall]]
Goes through =brew tap=, =brew list=, and =brew cask list= and generates a
master installation script for everything. Also installs all =pip2= and =pip3=
packages from [[../config/py2requirements.txt][py2requirements.txt]] and [[../config/py3requirements.txt][py3requirements.txt]].

* [[./pipup2][pipup2]]
Update pip2 packages in a sort of hackish way, run [[./mkmasterinstall][mkmasterinstall]]

* [[./pipup2][pipup3]] 
Update pip3 packages in a sort of hackish way, run [[./mkmasterinstall][mkmasterinstall]]

* [[./updates][updates]]
Run brewup, pipup2, pipup3 and [[./mkmasterinstall][mkmasterinstall]].

* [[./wfname][wfname]]
For Alfred workflows, read info.plist file and echo workflow name. Not so
relevant anymore.

* [[./wheres][wheres]]
An unnecessary function for finding files that can prooobably just be an alias?

* [[./workflow-build][workflow-build]]
[[https://github.com/deanishe][@deanishe]]'s [[https://gist.github.com/deanishe/b16f018119ef3fe951af][workflow-build.py]]

* [[./workflow-install][workflow-install]]
[[https://github.com/deanishe][@deanishe]]'s [[https://gist.github.com/deanishe/35faae3e7f89f629a94e][workflow-install.py]]
 


