#+TITLE: dotfiles

Just my dotfiles. Some of this is my own, a lot is inspired by or taken from
others' configs and adapted to my needs. This is a largely org-mode (and
therefore emacs) based dotfiles configuration. The configs are kept in org
files that are tangled to the right place on save. The tangle is in theory OS
aware (Linux or Darwin).

** Contents                                                      :toc:TOC_3:
  - [[#files][Files]]
    - [[#emacsd---emacs-config][emacs.d/ - emacs config]]
    - [[#rcorg---dotfiles-and-scripts][rc.org - dotfiles and scripts]]
    - [[#org-tangle---install-script][org-tangle - install script]]
  - [[#installation][Installation]]
    - [[#full][Full]]
    - [[#partial][Partial]]

** Files
*** [[./emacs.d/][emacs.d/]] - emacs config
An emacs configuration based largely on [[https://github.com/raxod502/straight.el][straight.el]], [[https://github.com/jwiegley/use-package][use-package]], [[https://github.com/emacs-evil/evil][evil-mode]],
and [[https://github.com/abo-abo/swiper][ivy]], with inspiration and code from [[https://github.com/syl20bnr/spacemacs][spacemacs]] and others' configs. The file
is tangled to ~init.el~ on save.
*** [[./rc.org][rc.org]] - dotfiles and scripts
A bunch of less complex or one-off configuration files and scripts I like to
keep handy, including configurations for [[https://github.com/dieggsy/dotfiles/blob/master/rc.org#tmux][tmux]] and [[https://github.com/dieggsy/dotfiles/blob/master/rc.org#i3][i3]] as well as a [[https://github.com/dieggsy/dotfiles/blob/master/rc.org#darktooththeme-cmus][cmus theme]],
among others. Some are my own but a lot of these are taken from or based on
config files from the internet. I'll pin down the sources one day.
*** [[./org-tangle][org-tangle]] - install script
A kind of messy script that makes use of ~emacs --script~ to run emacs-lisp code
as a shell script for initial installation of dotfiles, with support for
partial installation - you can choose which files or even headers from rc.org
to install.
** Installation
You should /probably/ have a fairly recent version of emacs, and potentially
org-mode. I tend to use a "bleeding edge" installation of emacs from source
(currently v27.0.50), and I've not tested this with older versions, though it
should work in theory.

Clone the repo to =~/dotfiles= (or wherever you'd like, but make sure the folder
remains named ~dotfiles~)

*NOTE:* The following will overwrite existing dotfiles/scripts, so be pretty damn
sure.

*** Full
Use provided script to install dotfiles and scripts.
#+begin_src sh
cd ~/dotfiles
./org-tangle
#+end_src

*** Partial
You can call the script with the filenames you'd like to install - say you want
just the emacs config:
#+begin_src sh
./org-tangle emacs.d/config.org
#+end_src
Any arguments not corresponding to a filename will search for a heading in
rc.org and tangle the files under that heading.

For example, say you want my emacs config, and /just/ my tmux and bspwm configs from
~rc.org~:
#+begin_src sh
./org-tangle emacs.d/config.org tmux bspwm
#+end_src

*Note:* Ideally for all of this to work optimally, there should be no ambiguity
between heading names in ~rc.org~. I'm working on it, but let me know if you spot
something.
