set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'joshdick/onedark.vim'
Plugin 'sheerun/vim-polyglot'
Plugin 'scrooloose/nerdtree'
Plugin 'Shougo/neocomplcache.vim'
" Plugin 'wincent/command-t'
" Plugin 'kien/ctrlp.vim'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'davidhalter/jedi-vim'
Plugin 'itchyny/lightline.vim'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
"Plugin 'tmhedberg/SimpylFold'
call vundle#end()
filetype plugin indent on
set laststatus=2
let g:neocomplcache_enable_at_startup=1
let g:ctrlp_working_path_mode = 0
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files . -co --exclude-standard', 'find %s -type f']
if (empty($TMUX))
  if (has("nvim"))
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  if (has("termguicolors"))
  	set termguicolors
  endif
endif
syntax on
set cursorline
set number
set hlsearch
let g:vim_markdown_folding_disabled = 1
" Enable folding
"set foldmethod=indent
"set foldlevel=99
set backspace=2 " make backspace work like most other apps
colorscheme onedark
highlight Comment cterm=italic
let mapleader = "\<Space>"
" nnoremap <leader><leader> :CommandTCommand<CR>
nnoremap <leader><leader> :ctrlp-commands<CR>
nnoremap <leader>ff :CtrlP ./<CR>
nnoremap <leader>fs :w<CR>
nnoremap <leader>bb :CtrlPMRU<CR>
au BufNewFile,BufRead *.py
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix |
    \ set smartindent

