set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Plugin 'VundleVim/Vundle.vim'
"Plugin 'joshdick/onedark.vim'
Plugin 'sheerun/vim-polyglot'
Plugin 'scrooloose/nerdtree'
Plugin 'Shougo/neocomplcache.vim'
Plugin 'wincent/command-t'
"Plugin 'kien/ctrlp.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'davidhalter/jedi-vim'
Plugin 'itchyny/lightline.vim'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
"Plugin 'tmhedberg/SimpylFold'
filetype on
set laststatus=2
let g:neocomplcache_enable_at_startup=1
if (empty($TMUX))
  if (has("nvim"))
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  if (has("termguicolors"))
  	set termguicolors
  endif
endif
syntax on
set cursorline
set number
set hlsearch
let g:vim_markdown_folding_disabled = 1
" Enable folding
"set foldmethod=indent
"set foldlevel=99
set backspace=2 " make backspace work like most other apps
colorscheme darktooth
highlight Comment cterm=italic
let mapleader = "\<Space>"
nnoremap <leader><leader> :CommandTCommand<CR>
nnoremap <leader>ff :CommandT<CR>
nnoremap <leader>fs :w<CR>
nnoremap <leader>bb :CommandTMRU<CR>
au BufNewFile,BufRead *.py
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix |
    \ set smartindent

