#!/usr/bin/bash

(key=$(date +%s.%N)

 if pgrep polybar; then
     echo "$key" > /tmp/polybar-backlight
     polybar-msg action "#backlight.module_show"
     brightness=$(printf "%0.f" `xbacklight -get`)
 fi

 if  [[ "$1" = "-" && $brightness -le 5 && $brightness -gt 1 ]] ||
        [[ "$1" = "+" && $brightness -lt 5 ]]; then
     xbacklight -set $(($brightness $1 1))
 elif ! [[ "$1" = "-" &&  $brightness -eq 1 ]]; then
     xbacklight -set $(($brightness $1 5))
 fi

 if pgrep polybar; then
     sleep 2
     [ "$key" = "$(</tmp/polybar-backlight)" ] &&
         polybar-msg action "#backlight.module_hide"
 fi) &>/dev/null &
