#!/usr/bin/env python3
import datetime
import calendar
import itertools
import locale
import webbrowser
import re
from subprocess import Popen, PIPE

today = datetime.date.today()
month = today.month
extra = (today.replace(day=1).weekday() + 1) % 7
lastday = calendar.monthrange(today.year, month)[1]

ENC = locale.getpreferredencoding()

days = ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"]

inp = days + [" "] * extra + list(
    map(lambda x: str(x).rjust(2), (range(1, lastday + 1)))
)


def chop(l, n):
    """Yield successive n-sized chunks from l."""
    for i in range(0, len(l), n):
        yield l[i:i + n]


chopped = list(chop(inp, 7))
chopped[-1] = chopped[-1] + [" "] * (7 - len(chopped[-1]))

ROFI_CMD = [
    "rofi", "-dmenu",
    "-mesg", f"{calendar.month_name[month]} {today.year}",
    "-theme", "calendar",
    "-theme-str", f"#listview{{lines:{len(chopped)};}}",
]

transposed = list(map(list, zip(*chopped)))
flattened = list(itertools.chain.from_iterable(transposed))
active = flattened.index(str(today.day).rjust(2))
inp = "\n".join(flattened)
p = Popen(ROFI_CMD + ["-a", str(active), "-selected-row", str(active)], stdin=PIPE,
          stdout=PIPE).communicate(input=inp.encode(ENC))[0].decode(ENC).strip()

if p and re.match("\d+", p):
    webbrowser.open(f"https://calendar.protonmail.com/u/0/day/{today.year}/{today.month}/{p}", new=2)
