#!/usr/bin/python

import json
import os
import locale
import re
import sys
from datetime import datetime
from subprocess import Popen, PIPE

ENV = os.environ.copy()
ENV['LC_ALL'] = 'C'
ENC = locale.getpreferredencoding()
ROFI_CMD = [
    "rofi",
    "-location", "3",
    "-dmenu", "-i",
    "-theme-str", "#inputbar {enabled:false;}",
    "-xoffset", "-15",
    "-markup-rows"
]


def run_rofi(args, extra_args, lines):
    return (Popen(args + extra_args, stdin=PIPE, stdout=PIPE, env=ENV)
            .communicate(input="\n".join(lines).encode(ENC))[0]
            .decode(ENC)).strip()


def main(args):
    print(args)
    with open("/tmp/darksky") as f:
        jdict = json.load(f)
    if args[1] == "hourly":
        run_rofi(ROFI_CMD,
                 ["-width", "340"],
                 ["<span color='#665C54'>"
                  f"{datetime.fromtimestamp(i['time']).strftime('%H:%M')}"
                  "</span>"
                  f"  {round(i['temperature'])}°  {re.sub('-day|-night', '', i['icon'])}"
                  for i in jdict['hourly']['data']][:24])
    elif args[1] == "daily":
        run_rofi(ROFI_CMD,
                 ["-width", "375"],
                 ["<span color='#665C54'>"
                  f"{datetime.fromtimestamp(i['time']).strftime('%a')}"
                  "</span>"
                  f"  {round(i['temperatureMin'])}°"
                  f" - {round(i['temperatureMax'])}° {re.sub('-day|-night', '', i['icon'])}"
                  for i in jdict['daily']['data']])


if __name__ == '__main__':
    main(sys.argv)
