#!/usr/bin/zsh
networks=$(iwctl station wlan0 get-networks)
connected=$(echo $networks | grep '>')
all=$(echo $networks | tail -n+5 |
          sed -E  "s/\x1B\[[0-9;]*[a-zA-Z]\*+//g; s/\x1B\[[0-9;]*[a-zA-Z]//g;" |
          cut -b5- |
          sed -E "s/\s{2,}/\t/g" |
          column -t -s $'\t' -o "\t")
selected=$(echo $all | rofi -p "iwd" -dmenu -i -theme menu $([[ -n "$connected" ]] && echo "-a 0") | cut -d$'\t' -f1)

if [[ -n "$selected" ]]; then
    password=$(rofi -dmenu -password -p "Password")
    if [[ -n "$password" ]]; then
        iwctl --passphrase=$password station wlan0 connect `echo $selected`
    fi
fi
