#!/usr/bin/bash

(key=$(date +%s.%N)

 if pgrep polybar; then
     echo "$key" > /tmp/polybar-volume
     polybar-msg action "#pulse.module_show"
 fi

 amixer -D pulse sset Master $1

 if pgrep polybar; then
     sleep 2
     [ "$key" = "$(</tmp/polybar-volume)" ] &&
         polybar-msg action "#pulse.module_hide"
 fi) &>/dev/null
