#!/usr/bin/env zsh
# message="Exit i3?"
[[ $(cat /proc/1/comm) == "systemd" ]] && logind=systemctl || logind=loginctl

declare -A cmds=([" lock"]="physlock"
                 ["﫼 logout"]="loginctl terminate-session self"
                 ["望 suspend"]="$logind suspend"
                 ["磻 reboot"]="$logind reboot"
                 ["襤 shutdown"]="$logind poweroff")

keys=(" lock" "﫼 logout" "望 suspend" "磻 reboot" "襤 shutdown")

usage () {
    echo "Usage: wm-exit [option]

Options:

$(printf '  %s  \n' "${keys[@]}")
  -rofi"
}

console-select () {
    for ((i = 1; i <= $#keys[@]; i++)); do
        echo $i. $keys[i]
    done
    echo -n "\nSelect an option (1-$((i - 1))): "
    read -r answer
    $cmds[$keys[$answer]]
}

rofi-select () {
    $cmds[$(printf '%s\n' "${keys[@]}" | rofi -dmenu -i -theme menu -theme-str "#inputbar {enabled:false;}")]
}


if [[ "$#" -eq 1 ]] && [[ "$1" = "-rofi" ]]; then
        rofi-select
elif [[ "$#" -eq 1 ]] && [[ -n "$cmds[$1]" ]]; then
        $cmds[$1]
elif [[ $# -eq 0 ]]; then
    console-select
else;
    usage
fi
