;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		counsel-M-x
		evil-find-char-to
		evil-inner-tag
		ivy-alt-done
		))

(setq mc/cmds-to-run-once
      '(
		))
