#!/usr/bin/env bash
export HOSTNAME=`hostname` # Gets rid of that annyoing question mark on top

# Welcome
echo "Welcome, diego"
export PS1="\[\e[91m\]\w\[\e[m\] \u\[\e[32m\]\\$\[\e[m\] "

eval $(thefuck --alias) #helps with fuckups

export EDITOR="emacsclient -t"
export ALTERNATE_EDITOR="vim"   

# Supposedly, sets up case insensitive bash completion. Seems to work
shopt -s nocaseglob
bind 'set completion-ignore-case on'

# Colors!

export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

# (gnu ls)
export LS_COLORS=$LS_COLORS:'di=0;36:ex=0;35:ln=1;31'

### Aliases
alias apps="cd /Applications"
alias cask="brew cask"
alias clc="clear"
alias def='dict -d gcide'
alias desk="cd /Users/diego/Desktop"
alias docs="cd /Users/diego/Documents/"
alias down="cd /Users/diego/Downloads/"
alias drive="cd /Users/diego/Google\ Drive"
alias drop="cd /Users/diego/Dropbox\ \(MIT\)"
alias edit="emacsclient -t"
alias editv="emacsclient -c"
alias f='find . -iname'
alias fd='find . -type d -iname'
alias ff='find . -type f -iname'
alias filecount="ls -1 | wc -l"
alias ls='ls -NX --group-directories-first --color=always'
alias lst="ls -t"
alias math='/Applications/Mathematica.app/Contents/MacOS/WolframKernel'
alias pep8="pep8 --first --ignore=E129,W503,E226"
alias piphere="pip install --target=./"
alias printers="lpstat -p | awk '{print $2}'"
alias resetb="source ~/.zshrc"
alias resetwifi="networksetup -setairportpower en0 off; sleep2;networksetup -setairportpower en0 on" 
alias run="python3"			  # I got super used to just tying 'run' in iPython
alias starwars="telnet towel.blinkenlights.nl" # heh 
alias pip=pip3
alias sudo='sudo '							   # recognize aliases 
alias sz="du -hs"							   # get folder/file size 
alias bashrc="$EDITOR ~/dotfiles/zshrc" 


py2() {
	workon py2
	export PYTHONSTARTUP=/Users/diego/.virtualenvs/py2/bin/.pythonrc.py
	alias run="python2"
}

out() {
	deactivate
	export PYTHONSTARTUP=$HOME/.pythonrc.py
	alias run="python3"
}

athena(){
	echo -n "Username: "
	read username
	ssh -Y "$username@athena.dialup.mit.edu"
}

# Make a file executable
mkexec(){
    chmod a+x "$@"
}

# Create/edit executable python script
pythonexec(){
    touch "$*"
    echo '#!/usr/local/bin/python3' | cat - "$*" > temp && mv temp "$*"
    sudo chmod a+x "$*"
    emacsclient -t "$*"
}

# Create/edit python script
pythonscript(){
    touch "$*"
    echo '#!/usr/local/bin/python3' | cat - "$*" > temp && mv temp "$*"
    emacsclient -t "$*"
}

# View only mode in emacs
ev() {
    emacsclient -t --eval "(view-file $1)"
}

# Edit Python 3 files
bam(){
    emacsclient -t "$1" --eval '(and (split-window-right) (windmove-right))' -f ipython --eval '(windmove-left)'
}

# Edit Python 2 files
ham(){
    emacsclient -t "$1" --eval '(and (split-window-right) (windmove-right))' -f ipython2 --eval '(windmove-left)'
}

export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

export PYTHONSTARTUP=$HOME/.pythonrc.py

# Set home page for lynx browser (and others I think)
export WWW_HOME='http://google.com'

export GREP_OPTIONS='--color=auto'

source "/usr/local/bin/virtualenvwrapper.sh"

export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
