"uh, i don't really use vim.
if (empty($TMUX))
  if (has("nvim"))
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  if (has("termguicolors"))
  	set termguicolors
  endif
endif
syntax on
colorscheme onedark
