#!/usr/bin/env zsh

# export PATH=/Users/diego/bin:/usr/local/sbin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/Cellar/zplug/2.2.1/bin:/usr/local/opt/zplug/bin:/Users/diego/bin:/usr/local/sbin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin

export PATH="$HOME/bin:/usr/local/sbin:/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
