#!/usr/bin/env zsh

# Path to your oh-my-zsh installation.
export ZSH=/Users/diego/.oh-my-zsh


# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="fino"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folderls

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git colored-man colorize github vagrant virtualenv pip python brew osx zsh-syntax-highlighting z)

# User configuration
export HOSTNAME=`hostname`
source $ZSH/oh-my-zsh.sh
echo "Welcome, Diego"
setopt GLOB_COMPLETE
setopt auto_cd
setopt histignoredups

function prompt_char {
  git branch >/dev/null 2>/dev/null && echo "±" && return
  echo '○'
}

function box_name {
    [ -f ~/.box-name ] && cat ~/.box-name || echo ${SHORT_HOST:-$HOST}
}

function virtualenv_info {
	[ $(virtualenv_prompt_info) ] && echo "%{$FG[239]%} env %{$reset_color%}$(virtualenv_prompt_info)"
}
local current_dir='${PWD/#$HOME/~}'
local git_info='$(git_prompt_info)'
local prompt_char='$(prompt_char)'
local venv_info='$(virtualenv_info)'

PROMPT="╭─%{$FG[040]%}%n%{$reset_color%} %{$FG[239]%}at%{$reset_color%} %{$FG[033]%}$(box_name)%{$reset_color%} %{$FG[239]%}in%{$reset_color%} %{$terminfo[bold]$FG[009]%}${current_dir}%{$reset_color%}${git_info}${venv_info}
╰─${prompt_char}%{$reset_color%} "


ZSH_THEME_GIT_PROMPT_PREFIX=" %{$FG[239]%}on%{$reset_color%} %{$fg[255]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_DIRTY="%{$FG[202]%}✘"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$FG[040]%}✔"

eval $(thefuck --alias)

export EDITOR="emacsclient -t" # Set emacs as default editor
export ALTERNATE_EDITOR="emacs -nw"

# export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
alias agenda="gcalcli agenda"
alias app="cd /Applications"
alias astronomy="cd /Users/diego/MIT\ 2015-2016/Spring/8.282"
alias bashe="emacsclient -t ~/.zshrc"
alias bin="cd /Users/diego/bin"
alias cask="brew cask"
alias chrome="open /Applications/Google\ Chrome.app"
alias clc="clear"
alias computation="cd /Users/diego/MIT\ 2015-2016/Spring/16.90"
alias des="cd /Users/diego/Desktop"
alias dict='dict -d gcide'
alias doc="cd /Users/diego/Documents/"
alias dow="cd /Users/diego/Downloads/"
alias drive="cd /Users/diego/Google\ Drive"
alias drop="cd /Users/diego/Dropbox\ \(MIT\)"
alias edit="emacsclient -t"
alias editv="emacsclient -c"
alias eve="open /Applications/EVE\ Launcher.app"
alias evernote='open /Applications/Evernote.app'
alias filecount="ls -1 | wc -l"
alias ipython2='export PYTHONSTARTUP=/Users/diego/.virtualenvs/py2/bin/.pythonrc.py && /Users/diego/.virtualenvs/py2/bin/ipython'
alias jpl="cd /Users/diego/Dropbox\ \(MIT\)/JPL"
alias ls='ls -NX --group-directories-first --color=always'
alias lsrt="ls -rt"
alias math='/Applications/Mathematica.app/Contents/MacOS/WolframKernel'
alias mit="cd /Users/diego/MIT\ 2015-2016/"
alias pep8="pep8 --first --ignore=E129,W503,E226"
alias printers="lpstat -p | awk '{print $2}'"
alias propulsion="cd /Users/diego/MIT\ 2015-2016/Spring/16.50"
alias python2='export PYTHONSTARTUP=/Users/diego/.virtualenvs/py2/bin/.pythonrc.py && /Users/diego/.virtualenvs/py2/bin/python2'
alias resetb="source ~/.zshrc; cp ~/.zshrc ~/Dropbox\ \(MIT\)/ComputerScripts/zshrc.txt"
alias resetwifi="networksetup -setairportpower en0 off; sleep2;networksetup -setairportpower en0 on"
alias run="python3"
alias screen="/usr/local/Cellar/screen/4.3.1/bin/screen"
alias setsize="printf '\e[8;24;80t'"
alias sizes="du -sh *"
alias starwars="telnet towel.blinkenlights.nl"
alias sudo='sudo '
alias sz="du -hs"
alias todo="more /Users/diego/Documents/TODO.txt"
alias todoe="emacsclient -t /Users/diego/Documents/TODO.txt"
alias twitter="rainbowstream"
alias watertimer='sleep 2400 && osascript -e "display notification \"Right Now\" with title \"Go get your water\""'
alias wgs="cd /Users/diego/MIT\ 2015-2016/Spring/WGS.221"
export LS_COLORS=$LS_COLORS:'di=0;36:ex=0;35:ln=1;31'
zstyle ':completion:*' list-colors 'di=0;36:ex=0;35:ln=1;31'


py2() {
	workon py2
	export PYTHONSTARTUP=/Users/diego/.virtualenvs/py2/bin/.pythonrc.py
	alias run="python2"
}

out() {
	deactivate
	export PYTHONSTARTUP=$HOME/.pythonrc.py
	alias run="python3"
}

athena(){
	echo -n "Username: "
	read username
	ssh -Y "$username@athena.dialup.mit.edu"
}

# Define something (opens dictionary app)
def() {
open "dict://$*"
}

# Make a file executable
mkexec(){
    chmod a+x "$@"
}

# Create/edit executable python script
pythonexec(){
    touch "$*"
    echo '#!/usr/local/bin/python3' | cat - "$*" > temp && mv temp "$*"
    sudo chmod a+x "$*"
    emacsclient -t "$*"
}

# Create/edit python script
pythonscript(){
    touch "$*"
    echo '#!/usr/local/bin/python3' | cat - "$*" > temp && mv temp "$*"
    emacsclient -t "$*"
}

# View only mode in emacs
ev() {
    emacsclient -t --eval "(view-file $1)"
}

# Edit Python 3 files
bam(){
    emacsclient -t "$1" --eval '(and (split-window-right) (windmove-right))' -f ipython --eval '(windmove-left)'
}

# Edit Python 2 files
ham(){
    emacsclient -t "$1" --eval '(and (split-window-right) (windmove-right))' -f ipython2 --eval '(windmove-left)'
}

# These used to download shit from athena servers, may be obsolete/modify for future use
# downprojfile(){
# scp dmundo@athena.dialup.mit.edu:/mit/dmundo/xfoilandavl/"$1" ~/Downloads/
# }

# upprojfile(){
# scp "$1" dmundo@athena.dialup.mit.edu:/mit/dmundo/xfoilandavl/
# }
export WWW_HOME='http://google.com'

export PATH="/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/usr/local/bin/python3:/Users/diego/Desktop:/Users/diego/Documents/Chords:/Users/diego/MIT 2015-2016/16.100:/usr/local/sbin:/usr/local/lib/python2.7/site-packages:/Users/diego/bin:/Applications/MATLAB_R2015b.app/bin:/usr/local/bin:/usr/local/Cellar/pygame/1.9.2a0/lib/python2.7/site-packages:/usr/local/bin/python3:/usr/local/bin:/usr/local/sbin:/usr/local/lib/python2.7/site-packages:/Users/diego/bin:/Applications/MATLAB_R2015b.app/bin"

source "/usr/local/bin/virtualenvwrapper.sh"
export PYTHONSTARTUP=$HOME/.pythonrc.py
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_STYLES[globbing]='fg=208'

export RTV_EDITOR='vim'
export RTV_URLVIEWER='urlview'
